# This is for LIO CleanUp

env: cleanup

env_args:
  num_agents: 2 # 5
  render: False
  episode_limit: 100 # 1000
  is_replay: False
  view_size: 4
  map: "default10"
  extra_args:
    random_spawn_point: False # spawn point & rotation
    random_spawn_rotation: 0 # None(empty): random, # 0:up, 1:down, 2:left, 3:right
    disable_rotation_action: True
    disable_left_right_action: False
    disable_fire_action: True
    obs_color: 'simplified' # full, simplified
    appleRespawnProbability: 0.5  # 10x10 0.3 | small 0.5
    thresholdDepletion: 0.6  # 10x10 0.4 | small 0.6
    thresholdRestoration: 0.0  # 10x10 0.0 | small 0.0
    wasteSpawnProbability: 0.5  # 10x10 0.5 | small 0.5

  # obs_height: 9  # For 7x7 map cleanup_small_sym
  # obs_width: 9
  # random_orientation: false
  # shuffle_spawn: false
  # beam_width: 3  # default 3
  # cleaning_penalty: 0.0
  # obs_cleaned_1hot: true
  # global_ref_point: null
  # map: 'cleanup_small_sym'  # 'cleanup_small_sym'|'cleanup_10x10_sym'
  # max_steps: 50  # small: 50 | 10x10: 50


test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 5050000